[package]
name = "midasio"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Utilities to read binary files in the MIDAS format"
readme = "README.md"
repository = "https://github.com/DJDuque/midasio"
keywords = ["midas", "daq", "data-acquisition", "physics"]
categories = ["parser-implementations", "science"]
documentation = "https://docs.rs/midasio"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
